[2024-12-10T22:59:03.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T22:59:03.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T22:48:55.856482+00:00 [queued]>
[2024-12-10T22:59:03.067+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T22:48:55.856482+00:00 [queued]>
[2024-12-10T22:59:03.068+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-10T22:59:03.083+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_parquet> on 2024-12-10 22:48:55.856482+00:00
[2024-12-10T22:59:03.138+0000] {standard_task_runner.py:72} INFO - Started process 1866 to run task
[2024-12-10T22:59:03.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Grab_NYC_Data_to_Minio', 'download_parquet', 'manual__2024-12-10T22:48:55.856482+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/minio.py', '--cfg-path', '/tmp/tmprywkj1hc']
[2024-12-10T22:59:03.153+0000] {standard_task_runner.py:105} INFO - Job 189: Subtask download_parquet
[2024-12-10T22:59:03.234+0000] {task_command.py:467} INFO - Running <TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T22:48:55.856482+00:00 [running]> on host 0805243c7015
[2024-12-10T22:59:03.306+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Grab_NYC_Data_to_Minio' AIRFLOW_CTX_TASK_ID='download_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T22:48:55.856482+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T22:48:55.856482+00:00'
[2024-12-10T22:59:03.308+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T22:59:03.309+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T22:59:03.309+0000] {logging_mixin.py:190} INFO - Current task name:download_parquet state:running start_date:2024-12-10 22:59:03.063819+00:00
[2024-12-10T22:59:03.309+0000] {logging_mixin.py:190} INFO - Dag name:Grab_NYC_Data_to_Minio and current dag run status:running
[2024-12-10T22:59:03.310+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T22:59:03.832+0000] {logging_mixin.py:190} INFO - Access denied (403 Forbidden). Check User-Agent or other headers.
[2024-12-10T22:59:03.836+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/minio.py", line 43, in download_parquet
    with urlopen(req) as response, open(local_file_path, 'wb') as out_file:
         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio.py", line 49, in download_parquet
    raise RuntimeError(f"Failed to download the Parquet file: {e}")
RuntimeError: Failed to download the Parquet file: HTTP Error 403: Forbidden
[2024-12-10T22:59:03.862+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T22:59:03.863+0000] {logging_mixin.py:190} INFO - Task start:2024-12-10 22:59:03.063819+00:00 end:2024-12-10 22:59:03.861596+00:00 duration:0.797777
[2024-12-10T22:59:03.864+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_parquet> dag:<DAG: Grab_NYC_Data_to_Minio> dagrun:<DagRun Grab_NYC_Data_to_Minio @ 2024-12-10 22:48:55.856482+00:00: manual__2024-12-10T22:48:55.856482+00:00, state:running, queued_at: 2024-12-10 22:48:55.927518+00:00. externally triggered: True>
[2024-12-10T22:59:03.864+0000] {logging_mixin.py:190} INFO - Failure caused by Failed to download the Parquet file: HTTP Error 403: Forbidden
[2024-12-10T22:59:03.864+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Grab_NYC_Data_to_Minio, task_id=download_parquet, run_id=manual__2024-12-10T22:48:55.856482+00:00, execution_date=20241210T224855, start_date=20241210T225903, end_date=20241210T225903
[2024-12-10T22:59:03.875+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T22:59:03.876+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 189 for task download_parquet (Failed to download the Parquet file: HTTP Error 403: Forbidden; 1866)
Traceback (most recent call last):
  File "/opt/airflow/dags/minio.py", line 43, in download_parquet
    with urlopen(req) as response, open(local_file_path, 'wb') as out_file:
         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio.py", line 49, in download_parquet
    raise RuntimeError(f"Failed to download the Parquet file: {e}")
RuntimeError: Failed to download the Parquet file: HTTP Error 403: Forbidden
[2024-12-10T22:59:03.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T22:59:03.960+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T22:59:03.965+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
