[2024-12-10T17:27:51.235+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T17:27:51.244+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T17:27:49.056347+00:00 [queued]>
[2024-12-10T17:27:51.248+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T17:27:49.056347+00:00 [queued]>
[2024-12-10T17:27:51.249+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-10T17:27:51.257+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_parquet> on 2024-12-10 17:27:49.056347+00:00
[2024-12-10T17:27:51.268+0000] {standard_task_runner.py:72} INFO - Started process 556 to run task
[2024-12-10T17:27:51.271+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Grab_NYC_Data_to_Minio', 'download_parquet', 'manual__2024-12-10T17:27:49.056347+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/minio.py', '--cfg-path', '/tmp/tmpv123l9jj']
[2024-12-10T17:27:51.272+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask download_parquet
[2024-12-10T17:27:51.324+0000] {task_command.py:467} INFO - Running <TaskInstance: Grab_NYC_Data_to_Minio.download_parquet manual__2024-12-10T17:27:49.056347+00:00 [running]> on host 0805243c7015
[2024-12-10T17:27:51.364+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Grab_NYC_Data_to_Minio' AIRFLOW_CTX_TASK_ID='download_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T17:27:49.056347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T17:27:49.056347+00:00'
[2024-12-10T17:27:51.365+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T17:27:51.365+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T17:27:51.366+0000] {logging_mixin.py:190} INFO - Current task name:download_parquet state:running start_date:2024-12-10 17:27:51.244694+00:00
[2024-12-10T17:27:51.366+0000] {logging_mixin.py:190} INFO - Dag name:Grab_NYC_Data_to_Minio and current dag run status:running
[2024-12-10T17:27:51.366+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T17:27:51.367+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/minio.py", line 37, in download_parquet
    response = requests.get(full_url, headers=headers, stream=True)
               ^^^^^^^^
NameError: name 'requests' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio.py", line 54, in download_parquet
    except requests.exceptions.RequestException as e:
           ^^^^^^^^
NameError: name 'requests' is not defined
[2024-12-10T17:27:51.373+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T17:27:51.373+0000] {logging_mixin.py:190} INFO - Task start:2024-12-10 17:27:51.244694+00:00 end:2024-12-10 17:27:51.373124+00:00 duration:0.12843
[2024-12-10T17:27:51.374+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_parquet> dag:<DAG: Grab_NYC_Data_to_Minio> dagrun:<DagRun Grab_NYC_Data_to_Minio @ 2024-12-10 17:27:49.056347+00:00: manual__2024-12-10T17:27:49.056347+00:00, state:running, queued_at: 2024-12-10 17:27:49.085597+00:00. externally triggered: True>
[2024-12-10T17:27:51.374+0000] {logging_mixin.py:190} INFO - Failure caused by name 'requests' is not defined
[2024-12-10T17:27:51.374+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Grab_NYC_Data_to_Minio, task_id=download_parquet, run_id=manual__2024-12-10T17:27:49.056347+00:00, execution_date=20241210T172749, start_date=20241210T172751, end_date=20241210T172751
[2024-12-10T17:27:51.381+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T17:27:51.383+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 187 for task download_parquet (name 'requests' is not defined; 556)
Traceback (most recent call last):
  File "/opt/airflow/dags/minio.py", line 37, in download_parquet
    response = requests.get(full_url, headers=headers, stream=True)
               ^^^^^^^^
NameError: name 'requests' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio.py", line 54, in download_parquet
    except requests.exceptions.RequestException as e:
           ^^^^^^^^
NameError: name 'requests' is not defined
[2024-12-10T17:27:51.417+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T17:27:51.428+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T17:27:51.431+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
