[2024-11-18T20:27:18.768+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:27:18.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:27:18.774+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:27:18.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:27:19.017+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:27:19.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:27:19.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:27:19.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.303 seconds
[2024-11-18T20:27:49.624+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:27:49.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:27:49.633+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:27:49.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:27:49.929+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:27:49.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:27:49.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:27:49.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.361 seconds
[2024-11-18T20:28:20.742+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:28:20.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:28:20.754+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:28:20.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:28:21.091+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:28:21.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:28:21.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:28:21.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.378 seconds
[2024-11-18T20:28:51.236+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:28:51.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:28:51.246+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:28:51.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:28:51.791+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:28:51.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:28:51.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:28:51.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.594 seconds
[2024-11-18T20:29:22.738+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:29:22.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:29:22.742+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:29:22.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:29:23.058+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:29:23.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:29:23.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:29:23.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.344 seconds
[2024-11-18T20:29:53.557+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:29:53.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:29:53.567+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:29:53.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:29:53.891+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:29:53.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:29:53.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:29:53.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.355 seconds
[2024-11-18T20:30:24.073+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:30:24.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:30:24.078+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:30:24.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:30:24.393+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:30:24.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:30:24.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:30:24.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.339 seconds
[2024-11-18T20:30:54.564+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:30:54.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:30:54.568+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:30:54.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:30:54.748+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:30:54.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:30:54.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:30:54.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.202 seconds
[2024-11-18T20:31:25.260+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:31:25.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:31:25.264+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:31:25.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:31:25.372+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:31:25.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:31:25.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:31:25.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.139 seconds
[2024-11-18T20:31:55.588+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:31:55.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:31:55.592+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:31:55.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:31:55.696+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:31:55.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:31:55.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:31:55.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.131 seconds
[2024-11-18T20:32:26.444+0000] {processor.py:186} INFO - Started process (PID=681) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:32:26.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:32:26.449+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:32:26.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:32:26.554+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:32:26.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:32:26.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:32:26.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.159 seconds
[2024-11-18T20:32:56.653+0000] {processor.py:186} INFO - Started process (PID=744) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:32:56.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:32:56.656+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:32:56.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:32:56.758+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:32:56.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:32:56.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:32:56.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.128 seconds
[2024-11-18T20:33:27.748+0000] {processor.py:186} INFO - Started process (PID=807) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:33:27.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:33:27.751+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:33:27.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:33:27.857+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:33:27.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:33:27.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:33:27.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.135 seconds
[2024-11-18T20:33:58.338+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:33:58.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:33:58.342+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:33:58.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:33:58.430+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:33:58.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:33:58.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:33:58.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.116 seconds
[2024-11-18T20:34:28.649+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:34:28.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:34:28.655+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:34:28.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:34:28.756+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:34:28.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:34:28.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:34:28.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.133 seconds
[2024-11-18T20:34:58.931+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:34:58.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:34:58.935+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:34:58.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:34:59.049+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:34:59.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:34:59.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:34:59.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.145 seconds
[2024-11-18T20:35:30.010+0000] {processor.py:186} INFO - Started process (PID=1059) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:35:30.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:35:30.014+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:35:30.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:35:30.146+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:35:30.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:35:30.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:35:30.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.173 seconds
[2024-11-18T20:36:00.620+0000] {processor.py:186} INFO - Started process (PID=1122) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:36:00.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:36:00.624+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:36:00.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:36:00.717+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:36:00.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:36:00.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:36:00.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.120 seconds
[2024-11-18T20:36:31.219+0000] {processor.py:186} INFO - Started process (PID=1185) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:36:31.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:36:31.223+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:36:31.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:36:31.307+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:36:31.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:36:31.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:36:31.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.115 seconds
[2024-11-18T20:37:01.632+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:37:01.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:37:01.636+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:37:01.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:37:01.780+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:37:01.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:37:01.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:37:01.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.178 seconds
[2024-11-18T20:37:32.020+0000] {processor.py:186} INFO - Started process (PID=1310) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:37:32.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:37:32.024+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:37:32.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:37:32.125+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:37:32.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:37:32.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:37:32.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.129 seconds
[2024-11-18T20:38:02.569+0000] {processor.py:186} INFO - Started process (PID=1373) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:38:02.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:38:02.572+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:38:02.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:38:02.750+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:38:02.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:38:02.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:38:02.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.240 seconds
[2024-11-18T20:38:33.086+0000] {processor.py:186} INFO - Started process (PID=1442) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:38:33.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:38:33.098+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:38:33.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:38:33.263+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:38:33.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:38:33.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:38:33.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.230 seconds
[2024-11-18T20:39:04.104+0000] {processor.py:186} INFO - Started process (PID=1505) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:39:04.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:39:04.107+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:39:04.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:39:04.209+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:39:04.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:39:04.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:39:04.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.126 seconds
[2024-11-18T20:39:35.065+0000] {processor.py:186} INFO - Started process (PID=1568) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:39:35.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:39:35.071+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:39:35.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:39:35.163+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:39:35.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:39:35.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:39:35.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.130 seconds
[2024-11-18T20:40:05.608+0000] {processor.py:186} INFO - Started process (PID=1631) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:40:05.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:40:05.614+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:40:05.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:40:05.704+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:40:05.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:40:05.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:40:05.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.117 seconds
[2024-11-18T20:40:36.562+0000] {processor.py:186} INFO - Started process (PID=1694) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:40:36.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:40:36.569+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:40:36.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:40:36.656+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:40:36.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:40:36.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:40:36.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.126 seconds
[2024-11-18T20:41:07.359+0000] {processor.py:186} INFO - Started process (PID=1757) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:41:07.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:41:07.480+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:41:07.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:41:07.659+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:41:07.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:41:07.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:41:07.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.355 seconds
[2024-11-18T20:41:37.721+0000] {processor.py:186} INFO - Started process (PID=1820) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:41:37.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:41:37.724+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:41:37.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:41:37.815+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:41:37.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:41:37.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:41:37.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.112 seconds
[2024-11-18T20:42:08.001+0000] {processor.py:186} INFO - Started process (PID=1883) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:42:08.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:42:08.005+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:42:08.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:42:08.089+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:42:08.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:42:08.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:42:08.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.122 seconds
[2024-11-18T20:42:38.746+0000] {processor.py:186} INFO - Started process (PID=1946) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:42:38.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:42:38.750+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:42:38.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:42:38.851+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:42:38.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:42:38.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:42:38.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.136 seconds
[2024-11-18T20:43:09.656+0000] {processor.py:186} INFO - Started process (PID=2009) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:43:09.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:43:09.661+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:43:09.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:43:09.768+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:43:09.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:43:09.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:43:09.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.157 seconds
[2024-11-18T20:43:40.095+0000] {processor.py:186} INFO - Started process (PID=2072) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:43:40.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:43:40.100+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:43:40.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:43:40.184+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:43:40.182+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:43:40.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:43:40.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.124 seconds
[2024-11-18T20:44:10.732+0000] {processor.py:186} INFO - Started process (PID=2135) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:44:10.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:44:10.736+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:44:10.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:44:10.845+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:44:10.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:44:10.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:44:10.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.146 seconds
[2024-11-18T20:44:41.329+0000] {processor.py:186} INFO - Started process (PID=2198) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:44:41.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:44:41.336+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:44:41.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:44:41.678+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:44:41.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:44:41.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:44:41.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.510 seconds
[2024-11-18T20:45:12.370+0000] {processor.py:186} INFO - Started process (PID=2261) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:45:12.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:45:12.374+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:45:12.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:45:12.493+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:45:12.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:45:12.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:45:12.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.152 seconds
[2024-11-18T20:47:05.158+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:47:05.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:47:05.163+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:47:05.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:47:05.407+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:47:05.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:47:05.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:47:05.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.289 seconds
[2024-11-18T20:47:35.811+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:47:35.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:47:35.819+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:47:35.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:47:36.114+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:47:36.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:47:36.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:47:36.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.334 seconds
[2024-11-18T20:48:06.753+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:48:06.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:48:06.769+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:48:06.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:48:07.086+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:48:07.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:48:07.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:48:07.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.377 seconds
[2024-11-18T20:48:37.121+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:48:37.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:48:37.123+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:48:37.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:48:37.400+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:48:37.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:48:37.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:48:37.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.293 seconds
[2024-11-18T20:49:07.695+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:49:07.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:49:07.701+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:49:07.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:49:08.032+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:49:08.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:49:08.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:49:08.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.383 seconds
[2024-11-18T20:49:38.282+0000] {processor.py:186} INFO - Started process (PID=363) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:49:38.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:49:38.290+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:49:38.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:49:38.613+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:49:38.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:49:38.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:49:38.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.353 seconds
[2024-11-18T20:50:09.271+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:50:09.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:50:09.282+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:50:09.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:50:09.630+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:50:09.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:50:09.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:50:09.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.393 seconds
[2024-11-18T20:50:39.828+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:50:39.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:50:39.844+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:50:39.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:50:40.080+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:50:40.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:50:40.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:50:40.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.293 seconds
[2024-11-18T20:51:10.738+0000] {processor.py:186} INFO - Started process (PID=552) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:51:10.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:51:10.745+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:51:10.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:51:10.854+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:51:10.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:51:10.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:51:10.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.134 seconds
[2024-11-18T20:51:40.978+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:51:40.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:51:41.002+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:51:41.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:51:41.106+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:51:41.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:51:41.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:51:41.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.152 seconds
[2024-11-18T20:52:11.713+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:52:11.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:52:11.719+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:52:11.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:52:11.875+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:52:11.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:52:11.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:52:11.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.183 seconds
[2024-11-18T20:52:42.235+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:52:42.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:52:42.243+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:52:42.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:52:42.393+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:52:42.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:52:42.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:52:42.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.199 seconds
[2024-11-18T20:53:12.918+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:53:12.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:53:12.926+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:53:12.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:53:13.040+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:53:13.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:53:13.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:53:13.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.146 seconds
[2024-11-18T20:53:43.142+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:53:43.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:53:43.147+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:53:43.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:53:43.262+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:53:43.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:53:43.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:53:43.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.139 seconds
[2024-11-18T20:54:13.998+0000] {processor.py:186} INFO - Started process (PID=929) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:54:14.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:54:14.016+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:54:14.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:54:14.140+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:54:14.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:54:14.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:54:14.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.168 seconds
[2024-11-18T20:54:45.171+0000] {processor.py:186} INFO - Started process (PID=992) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:54:45.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:54:45.186+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:54:45.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:54:45.286+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:54:45.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:54:45.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:54:45.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.160 seconds
[2024-11-18T20:55:15.899+0000] {processor.py:186} INFO - Started process (PID=1055) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:55:15.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:55:15.907+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:55:15.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:55:16.017+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:55:16.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:55:16.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:55:16.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.143 seconds
[2024-11-18T20:55:46.345+0000] {processor.py:186} INFO - Started process (PID=1118) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:55:46.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:55:46.350+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:55:46.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:55:46.503+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:55:46.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:55:46.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:55:46.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.197 seconds
[2024-11-18T20:56:17.431+0000] {processor.py:186} INFO - Started process (PID=1181) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:56:17.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:56:17.439+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:56:17.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:56:17.571+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:56:17.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:56:17.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:56:17.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.177 seconds
[2024-11-18T20:56:48.626+0000] {processor.py:186} INFO - Started process (PID=1244) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:56:48.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:56:48.652+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:56:48.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:56:48.861+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:56:48.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:56:48.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:56:48.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.258 seconds
[2024-11-18T20:57:19.390+0000] {processor.py:186} INFO - Started process (PID=1307) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:57:19.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:57:19.412+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:57:19.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:57:19.631+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:57:19.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:57:19.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:57:19.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.291 seconds
[2024-11-18T20:57:49.995+0000] {processor.py:186} INFO - Started process (PID=1370) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:57:49.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:57:50.003+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:57:50.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:57:50.127+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:57:50.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:57:50.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:57:50.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.160 seconds
[2024-11-18T20:58:20.708+0000] {processor.py:186} INFO - Started process (PID=1433) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:58:20.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:58:20.729+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:58:20.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:58:20.925+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:58:20.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:58:20.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:58:20.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.247 seconds
[2024-11-18T20:58:51.639+0000] {processor.py:186} INFO - Started process (PID=1496) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:58:51.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:58:51.645+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:58:51.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:58:51.806+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:58:51.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:58:51.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:58:51.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.221 seconds
[2024-11-18T20:59:22.490+0000] {processor.py:186} INFO - Started process (PID=1559) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:59:22.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:59:22.496+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:59:22.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:59:22.600+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:59:22.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:59:22.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:59:22.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.143 seconds
[2024-11-18T20:59:53.366+0000] {processor.py:186} INFO - Started process (PID=1622) to work on /opt/airflow/dags/minio.py
[2024-11-18T20:59:53.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T20:59:53.378+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:59:53.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T20:59:53.573+0000] {logging_mixin.py:190} INFO - [2024-11-18T20:59:53.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T20:59:53.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T20:59:53.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.265 seconds
[2024-11-18T21:00:24.752+0000] {processor.py:186} INFO - Started process (PID=1685) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:00:24.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:00:24.789+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:00:24.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:00:25.465+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:00:25.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:00:25.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:00:25.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.859 seconds
[2024-11-18T21:00:56.278+0000] {processor.py:186} INFO - Started process (PID=1749) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:00:56.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:00:56.318+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:00:56.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:00:57.268+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:00:57.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:00:57.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:00:57.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 1.099 seconds
[2024-11-18T21:01:27.699+0000] {processor.py:186} INFO - Started process (PID=1815) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:01:27.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:01:27.702+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:01:27.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:01:28.082+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:01:28.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:01:28.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:01:28.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.408 seconds
[2024-11-18T21:02:01.491+0000] {processor.py:186} INFO - Started process (PID=1886) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:02:01.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:02:01.495+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:02:01.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:02:01.811+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:02:01.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:02:01.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:02:01.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.489 seconds
[2024-11-18T21:02:32.057+0000] {processor.py:186} INFO - Started process (PID=1949) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:02:32.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:02:32.062+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:02:32.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:02:32.272+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:02:32.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:02:32.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:02:32.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.247 seconds
[2024-11-18T21:03:02.452+0000] {processor.py:186} INFO - Started process (PID=2012) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:03:02.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:03:02.455+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:03:02.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:03:02.534+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:03:02.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:03:02.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:03:02.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.100 seconds
[2024-11-18T21:03:32.963+0000] {processor.py:186} INFO - Started process (PID=2070) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:03:32.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:03:32.975+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:03:32.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:03:33.157+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:03:33.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:03:33.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:03:33.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.226 seconds
[2024-11-18T21:04:03.237+0000] {processor.py:186} INFO - Started process (PID=2134) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:04:03.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:04:03.244+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:04:03.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:04:03.413+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:04:03.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:04:03.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:04:03.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.243 seconds
[2024-11-18T21:04:33.797+0000] {processor.py:186} INFO - Started process (PID=2196) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:04:33.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:04:33.824+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:04:33.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:04:34.004+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:04:33.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:04:34.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:04:34.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.263 seconds
[2024-11-18T21:05:04.312+0000] {processor.py:186} INFO - Started process (PID=2259) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:05:04.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:05:04.319+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:05:04.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:05:04.567+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:05:04.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:05:04.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:05:04.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.302 seconds
[2024-11-18T21:05:35.312+0000] {processor.py:186} INFO - Started process (PID=2321) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:05:35.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:05:35.324+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:05:35.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:05:35.467+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:05:35.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:05:35.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:05:35.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.202 seconds
[2024-11-18T21:06:06.530+0000] {processor.py:186} INFO - Started process (PID=2384) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:06:06.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:06:06.553+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:06:06.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:06:06.699+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:06:06.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:06:06.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:06:06.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.208 seconds
[2024-11-18T21:06:37.592+0000] {processor.py:186} INFO - Started process (PID=2447) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:06:37.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:06:37.604+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:06:37.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:06:37.764+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:06:37.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:06:37.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:06:37.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.199 seconds
[2024-11-18T21:07:07.951+0000] {processor.py:186} INFO - Started process (PID=2509) to work on /opt/airflow/dags/minio.py
[2024-11-18T21:07:07.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-18T21:07:07.958+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:07:07.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-18T21:07:08.088+0000] {logging_mixin.py:190} INFO - [2024-11-18T21:07:08.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-18T21:07:08.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-18T21:07:08.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.165 seconds
